# Generated by Django 4.0.3 on 2022-04-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='photo',
            field=models.ImageField(default='photo', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classes',
            name='number',
            field=models.CharField(default='№', max_length=20),
        ),
    ]
