# Generated by Django 4.0.3 on 2022-05-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='school_number',
            field=models.IntegerField(blank=True, verbose_name='Номер школы'),
        ),
    ]
