# Generated by Django 4.0.3 on 2022-05-17 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='schools',
            name='school_name',
            field=models.CharField(blank=True, default='ГБОУ', max_length=150, null=True, verbose_name='Название школы'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='full_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classes', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='doneworks',
            name='comment_from_student',
            field=models.CharField(default='Комментарий', max_length=255, verbose_name='Комментарий от студента'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='comment_from_teacher',
            field=models.CharField(default='Комментарий', max_length=255, verbose_name='Комментарий от учителя'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Студент', to=settings.AUTH_USER_MODEL, verbose_name='Идентификация студента'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Учитель', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
    ]
