# Generated by Django 4.0.3 on 2022-05-18 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_grades_status_schools_school_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='school_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schools', verbose_name='Номер школы'),
        ),
        migrations.AddField(
            model_name='works',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер задания'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Номер класса'),
        ),
    ]
