# Generated by Django 4.0.3 on 2022-05-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auth_school_number_works_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_num',
            field=models.IntegerField(default=1, unique=True, verbose_name='Номер школы'),
        ),
        migrations.AlterField(
            model_name='works',
            name='number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Номер задания'),
        ),
    ]
