# Generated by Django 4.0.3 on 2022-05-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_auth_school_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneworks',
            name='comment_from_student',
            field=models.CharField(default='Комментарий', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='grades',
            name='comment_from_teacher',
            field=models.CharField(default='Комментарий', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='patronymic',
            field=models.CharField(max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='school_number',
            field=models.IntegerField(null=True, verbose_name='Номер школы'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_letter',
            field=models.CharField(default='буква', max_length=5, verbose_name='Буква класса'),
        ),
        migrations.AlterField(
            model_name='doneworks',
            name='done_work',
            field=models.ImageField(default='Готовая карта', upload_to='done_map/%Y/%m/%d/', verbose_name='Готовая работа'),
        ),
        migrations.AlterField(
            model_name='works',
            name='legend',
            field=models.CharField(default='Легенда', max_length=255, verbose_name='Легенда'),
        ),
        migrations.AlterField(
            model_name='works',
            name='task',
            field=models.CharField(default='Задание', max_length=255, verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='works',
            name='work',
            field=models.ImageField(default='Базовая карта', upload_to='base_maps/%Y/%m/%d/', verbose_name='Работа'),
        ),
    ]
