# Generated by Django 4.0.3 on 2022-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_doneworks_comment_from_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.EmailField(max_length=150, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='patronymic',
            field=models.CharField(max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
