# Generated by Django 4.0.3 on 2022-05-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_works_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='legend',
            field=models.CharField(blank=True, max_length=511, verbose_name='Легенда'),
        ),
    ]
