# Generated by Django 4.0.3 on 2022-05-21 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_works_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='school_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schools', verbose_name='Номер школы'),
        ),
        migrations.AlterField(
            model_name='works',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер задания'),
        ),
    ]
