# Generated by Django 4.0.3 on 2022-05-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_works_school_number_alter_works_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='task',
            field=models.CharField(default='Задание', max_length=511, verbose_name='Задание'),
        ),
    ]
