# Generated by Django 4.0.3 on 2022-05-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_works_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='work_name',
            field=models.CharField(default='Задание', max_length=50, verbose_name='Название задания'),
            preserve_default=False,
        ),
    ]
