# Generated by Django 4.0.3 on 2022-05-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_works_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='comment_from_teacher',
            field=models.CharField(max_length=255, verbose_name='Комментарий от учителя'),
        ),
    ]
