# Generated by Django 4.0.3 on 2022-05-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_grades_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='student_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.classes', verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
