# Generated by Django 4.0.3 on 2022-05-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_grades_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='student_class',
        ),
    ]
