# Generated by Django 4.0.3 on 2022-05-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_works_for_class_alter_works_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doneworks',
            name='comment_from_student',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Комментарий от ученика'),
        ),
        migrations.AlterField(
            model_name='doneworks',
            name='comment_from_teacher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий от учителя'),
        ),
    ]
